export function getQueryInput() {
    return document.getElementById('query').value;
}

export function prepareForSearch(text) {
    return text.normalize("NFKC").toLowerCase()
        .replace(/\b(\w+)[’']s\b/gi, '$1')
        .trim();
}

export function escapeHtml(str) {
    return str.replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;");
}

// Mapping from UMLS semantic type abbreviations and TUIs to human-friendly names
// The object includes entries for both the short code (e.g. "aapp") and the TUI
// (e.g. "T116").  Unknown codes are returned as-is.
export const SEMANTIC_TYPE_MAP = {
    aapp: 'Amino Acid, Peptide, or Protein',
    T116: 'Amino Acid, Peptide, or Protein',
    acab: 'Acquired Abnormality',
    T020: 'Acquired Abnormality',
    acty: 'Activity',
    T052: 'Activity',
    aggp: 'Age Group',
    T100: 'Age Group',
    amas: 'Amino Acid Sequence',
    T087: 'Amino Acid Sequence',
    amph: 'Amphibian',
    T011: 'Amphibian',
    anab: 'Anatomical Abnormality',
    T190: 'Anatomical Abnormality',
    anim: 'Animal',
    T008: 'Animal',
    anst: 'Anatomical Structure',
    T017: 'Anatomical Structure',
    antb: 'Antibiotic',
    T195: 'Antibiotic',
    arch: 'Archaeon',
    T194: 'Archaeon',
    bacs: 'Biologically Active Substance',
    T123: 'Biologically Active Substance',
    bact: 'Bacterium',
    T007: 'Bacterium',
    bdsu: 'Body Substance',
    T031: 'Body Substance',
    bdsy: 'Body System',
    T022: 'Body System',
    bhvr: 'Behavior',
    T053: 'Behavior',
    biof: 'Biologic Function',
    T038: 'Biologic Function',
    bird: 'Bird',
    T012: 'Bird',
    blor: 'Body Location or Region',
    T029: 'Body Location or Region',
    bmod: 'Biomedical Occupation or Discipline',
    T091: 'Biomedical Occupation or Discipline',
    bodm: 'Biomedical or Dental Material',
    T122: 'Biomedical or Dental Material',
    bpoc: 'Body Part, Organ, or Organ Component',
    T023: 'Body Part, Organ, or Organ Component',
    bsoj: 'Body Space or Junction',
    T030: 'Body Space or Junction',
    celc: 'Cell Component',
    T026: 'Cell Component',
    celf: 'Cell Function',
    T043: 'Cell Function',
    cell: 'Cell',
    T025: 'Cell',
    cgab: 'Congenital Abnormality',
    T019: 'Congenital Abnormality',
    chem: 'Chemical',
    T103: 'Chemical',
    chvf: 'Chemical Viewed Functionally',
    T120: 'Chemical Viewed Functionally',
    chvs: 'Chemical Viewed Structurally',
    T104: 'Chemical Viewed Structurally',
    clas: 'Classification',
    T185: 'Classification',
    clna: 'Clinical Attribute',
    T201: 'Clinical Attribute',
    clnd: 'Clinical Drug',
    T200: 'Clinical Drug',
    cnce: 'Conceptual Entity',
    T077: 'Conceptual Entity',
    comd: 'Cell or Molecular Dysfunction',
    T049: 'Cell or Molecular Dysfunction',
    crbs: 'Carbohydrate Sequence',
    T088: 'Carbohydrate Sequence',
    diap: 'Diagnostic Procedure',
    T060: 'Diagnostic Procedure',
    dora: 'Daily or Recreational Activity',
    T056: 'Daily or Recreational Activity',
    drdd: 'Drug Delivery Device',
    T203: 'Drug Delivery Device',
    dsyn: 'Disease or Syndrome',
    T047: 'Disease or Syndrome',
    edac: 'Educational Activity',
    T065: 'Educational Activity',
    eehu: 'Environmental Effect of Humans',
    T069: 'Environmental Effect of Humans',
    elii: 'Element, Ion, or Isotope',
    T196: 'Element, Ion, or Isotope',
    emod: 'Experimental Model of Disease',
    T050: 'Experimental Model of Disease',
    emst: 'Embryonic Structure',
    T018: 'Embryonic Structure',
    enty: 'Entity',
    T071: 'Entity',
    enzy: 'Enzyme',
    T126: 'Enzyme',
    euka: 'Eukaryote',
    T204: 'Eukaryote',
    evnt: 'Event',
    T051: 'Event',
    famg: 'Family Group',
    T099: 'Family Group',
    ffas: 'Fully Formed Anatomical Structure',
    T021: 'Fully Formed Anatomical Structure',
    fish: 'Fish',
    T013: 'Fish',
    fndg: 'Finding',
    T033: 'Finding',
    fngs: 'Fungus',
    T004: 'Fungus',
    food: 'Food',
    T168: 'Food',
    ftcn: 'Functional Concept',
    T169: 'Functional Concept',
    genf: 'Genetic Function',
    T045: 'Genetic Function',
    geoa: 'Geographic Area',
    T083: 'Geographic Area',
    gngm: 'Gene or Genome',
    T028: 'Gene or Genome',
    gora: 'Governmental or Regulatory Activity',
    T064: 'Governmental or Regulatory Activity',
    grpa: 'Group Attribute',
    T102: 'Group Attribute',
    grup: 'Group',
    T096: 'Group',
    hcpp: 'Human-caused Phenomenon or Process',
    T068: 'Human-caused Phenomenon or Process',
    hcro: 'Health Care Related Organization',
    T093: 'Health Care Related Organization',
    hlca: 'Health Care Activity',
    T058: 'Health Care Activity',
    hops: 'Hazardous or Poisonous Substance',
    T131: 'Hazardous or Poisonous Substance',
    horm: 'Hormone',
    T125: 'Hormone',
    humn: 'Human',
    T016: 'Human',
    idcn: 'Idea or Concept',
    T078: 'Idea or Concept',
    imft: 'Immunologic Factor',
    T129: 'Immunologic Factor',
    inbe: 'Individual Behavior',
    T055: 'Individual Behavior',
    inch: 'Inorganic Chemical',
    T197: 'Inorganic Chemical',
    inpo: 'Injury or Poisoning',
    T037: 'Injury or Poisoning',
    inpr: 'Intellectual Product',
    T170: 'Intellectual Product',
    irda: 'Indicator, Reagent, or Diagnostic Aid',
    T130: 'Indicator, Reagent, or Diagnostic Aid',
    lang: 'Language',
    T171: 'Language',
    lbpr: 'Laboratory Procedure',
    T059: 'Laboratory Procedure',
    lbtr: 'Laboratory or Test Result',
    T034: 'Laboratory or Test Result',
    mamm: 'Mammal',
    T015: 'Mammal',
    mbrt: 'Molecular Biology Research Technique',
    T063: 'Molecular Biology Research Technique',
    mcha: 'Machine Activity',
    T066: 'Machine Activity',
    medd: 'Medical Device',
    T074: 'Medical Device',
    menp: 'Mental Process',
    T041: 'Mental Process',
    mnob: 'Manufactured Object',
    T073: 'Manufactured Object',
    mobd: 'Mental or Behavioral Dysfunction',
    T048: 'Mental or Behavioral Dysfunction',
    moft: 'Molecular Function',
    T044: 'Molecular Function',
    mosq: 'Molecular Sequence',
    T085: 'Molecular Sequence',
    neop: 'Neoplastic Process',
    T191: 'Neoplastic Process',
    nnon: 'Nucleic Acid, Nucleoside, or Nucleotide',
    T114: 'Nucleic Acid, Nucleoside, or Nucleotide',
    npop: 'Natural Phenomenon or Process',
    T070: 'Natural Phenomenon or Process',
    nusq: 'Nucleotide Sequence',
    T086: 'Nucleotide Sequence',
    ocac: 'Occupational Activity',
    T057: 'Occupational Activity',
    ocdi: 'Occupation or Discipline',
    T090: 'Occupation or Discipline',
    orch: 'Organic Chemical',
    T109: 'Organic Chemical',
    orga: 'Organism Attribute',
    T032: 'Organism Attribute',
    orgf: 'Organism Function',
    T040: 'Organism Function',
    orgm: 'Organism',
    T001: 'Organism',
    orgt: 'Organization',
    T092: 'Organization',
    ortf: 'Organ or Tissue Function',
    T042: 'Organ or Tissue Function',
    patf: 'Pathologic Function',
    T046: 'Pathologic Function',
    phob: 'Physical Object',
    T072: 'Physical Object',
    phpr: 'Phenomenon or Process',
    T067: 'Phenomenon or Process',
    phsf: 'Physiologic Function',
    T039: 'Physiologic Function',
    phsu: 'Pharmacologic Substance',
    T121: 'Pharmacologic Substance',
    plnt: 'Plant',
    T002: 'Plant',
    podg: 'Patient or Disabled Group',
    T101: 'Patient or Disabled Group',
    popg: 'Population Group',
    T098: 'Population Group',
    prog: 'Professional or Occupational Group',
    T097: 'Professional or Occupational Group',
    pros: 'Professional Society',
    T094: 'Professional Society',
    qlco: 'Qualitative Concept',
    T080: 'Qualitative Concept',
    qnco: 'Quantitative Concept',
    T081: 'Quantitative Concept',
    rcpt: 'Receptor',
    T192: 'Receptor',
    rept: 'Reptile',
    T014: 'Reptile',
    resa: 'Research Activity',
    T062: 'Research Activity',
    resd: 'Research Device',
    T075: 'Research Device',
    rnlw: 'Regulation or Law',
    T089: 'Regulation or Law',
    sbst: 'Substance',
    T167: 'Substance',
    shro: 'Self-help or Relief Organization',
    T095: 'Self-help or Relief Organization',
    socb: 'Social Behavior',
    T054: 'Social Behavior',
    sosy: 'Sign or Symptom',
    T184: 'Sign or Symptom',
    spco: 'Spatial Concept',
    T082: 'Spatial Concept',
    tisu: 'Tissue',
    T024: 'Tissue',
    tmco: 'Temporal Concept',
    T079: 'Temporal Concept',
    topp: 'Therapeutic or Preventive Procedure',
    T061: 'Therapeutic or Preventive Procedure',
    virs: 'Virus',
    T005: 'Virus',
    vita: 'Vitamin',
    T127: 'Vitamin',
    vtbt: 'Vertebrate',
    T010: 'Vertebrate'
};

export function getSemanticTypeName(code) {
    return SEMANTIC_TYPE_MAP[code] || SEMANTIC_TYPE_MAP[code.toLowerCase()] || code;
}
