WHENEVER SQLERROR EXIT -1
SET ECHO ON

CREATE INDEX X_MRCONSO_CUI ON MRCONSO(CUI)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRCONSO ADD CONSTRAINT X_MRCONSO_PK PRIMARY KEY (AUI)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_SUI ON MRCONSO(SUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_LUI ON MRCONSO(LUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_CODE ON MRCONSO(CODE)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_SAB_TTY ON MRCONSO(SAB,TTY)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_SCUI ON MRCONSO(SCUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_SDUI ON MRCONSO(SDUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCONSO_STR ON MRCONSO(STR)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCXT_CUI ON MRCXT(CUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCXT_AUI ON MRCXT(AUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCXT_SAB ON MRCXT(SAB)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRDEF_CUI ON MRDEF(CUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRDEF_AUI ON MRDEF(AUI)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRDEF ADD CONSTRAINT X_MRDEF_PK PRIMARY KEY (ATUI)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRDEF_SAB ON MRDEF(SAB)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIER_CUI ON MRHIER(CUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIER_AUI ON MRHIER(AUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIER_SAB ON MRHIER(SAB)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIER_PTR ON MRHIER(PTR)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIER_PAUI ON MRHIER(PAUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIST_CUI ON MRHIST(CUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIST_SOURCEUI ON MRHIST(SOURCEUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRHIST_SAB ON MRHIST(SAB)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRRANK ADD CONSTRAINT X_MRRANK_PK PRIMARY KEY (SAB,TTY)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRREL_CUI1 ON MRREL(CUI1)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRREL_AUI1 ON MRREL(AUI1)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRREL_CUI2 ON MRREL(CUI2)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRREL_AUI2 ON MRREL(AUI2)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRREL ADD CONSTRAINT X_MRREL_PK PRIMARY KEY (RUI)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRREL_SAB ON MRREL(SAB)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRSAB ADD CONSTRAINT X_MRSAB_PK PRIMARY KEY (VSAB)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSAB_RSAB ON MRSAB(RSAB)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSAT_CUI ON MRSAT(CUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSAT_METAUI ON MRSAT(METAUI)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRSAT ADD CONSTRAINT X_MRSAT_PK PRIMARY KEY (ATUI)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSAT_SAB ON MRSAT(SAB)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSAT_ATN ON MRSAT(ATN)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSTY_CUI ON MRSTY(CUI)
PCTFREE 10 COMPUTE STATISTICS;

ALTER TABLE MRSTY ADD CONSTRAINT X_MRSTY_PK PRIMARY KEY (ATUI)
USING INDEX PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRSTY_STY ON MRSTY(STY)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXNS_ENG_NSTR ON MRXNS_ENG(NSTR)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXNW_ENG_NWD ON MRXNW_ENG(NWD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_BAQ_WD ON MRXW_BAQ(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_CHI_WD ON MRXW_CHI(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_CZE_WD ON MRXW_CZE(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_DAN_WD ON MRXW_DAN(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_DUT_WD ON MRXW_DUT(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_ENG_WD ON MRXW_ENG(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_EST_WD ON MRXW_EST(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_FIN_WD ON MRXW_FIN(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_FRE_WD ON MRXW_FRE(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_GER_WD ON MRXW_GER(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_GRE_WD ON MRXW_GRE(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_HEB_WD ON MRXW_HEB(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_HUN_WD ON MRXW_HUN(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_ITA_WD ON MRXW_ITA(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_JPN_WD ON MRXW_JPN(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_KOR_WD ON MRXW_KOR(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_LAV_WD ON MRXW_LAV(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_NOR_WD ON MRXW_NOR(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_POL_WD ON MRXW_POL(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_POR_WD ON MRXW_POR(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_RUS_WD ON MRXW_RUS(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_SCR_WD ON MRXW_SCR(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_SPA_WD ON MRXW_SPA(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_SWE_WD ON MRXW_SWE(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRXW_TUR_WD ON MRXW_TUR(WD)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_AMBIGSUI_SUI ON AMBIGSUI(SUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_AMBIGLUI_LUI ON AMBIGLUI(LUI)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRAUI_CUI2 ON MRAUI(CUI2)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRCUI_CUI2 ON MRCUI(CUI2)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX X_MRMAP_MAPSETCUI ON MRMAP(MAPSETCUI)
PCTFREE 10 COMPUTE STATISTICS;

