WHENEVER SQLERROR EXIT -1
SET ECHO ON

ALTER SESSION SET NLS_LENGTH_SEMANTICS='CHAR';

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRCOLS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRCOLS (
    COL	varchar2(40),
    DES	varchar2(200),
    REF	varchar2(40),
    MIN	integer,
    AV	numeric(5,2),
    MAX	integer,
    FIL	varchar2(50),
    DTY	varchar2(40)
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRCONSO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRCONSO (
    CUI	char(8) NOT NULL,
    LAT	char(3) NOT NULL,
    TS	char(1) NOT NULL,
    LUI	varchar2(10) NOT NULL,
    STT	varchar2(3) NOT NULL,
    SUI	varchar2(10) NOT NULL,
    ISPREF	char(1) NOT NULL,
    AUI	varchar2(9) NOT NULL,
    SAUI	varchar2(50),
    SCUI	varchar2(100),
    SDUI	varchar2(100),
    SAB	varchar2(40) NOT NULL,
    TTY	varchar2(40) NOT NULL,
    CODE	varchar2(100) NOT NULL,
    STR	varchar2(3000) NOT NULL,
    SRL	integer NOT NULL,
    SUPPRESS	char(1) NOT NULL,
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRCUI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRCUI (
    CUI1	char(8) NOT NULL,
    VER	varchar2(10) NOT NULL,
    REL	varchar2(4) NOT NULL,
    RELA	varchar2(100),
    MAPREASON	varchar2(4000),
    CUI2	char(8),
    MAPIN	char(1)
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRCXT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRCXT (
    CUI	char(8),
    SUI	varchar2(10),
    AUI	varchar2(9),
    SAB	varchar2(40),
    CODE	varchar2(100),
    CXN	integer,
    CXL	char(3),
    RANK	integer,
    CXS	varchar2(3000),
    CUI2	char(8),
    AUI2	varchar2(9),
    HCD	varchar2(100),
    RELA	varchar2(100),
    XC	varchar2(1),
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRDEF'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRDEF (
    CUI	char(8) NOT NULL,
    AUI	varchar2(9) NOT NULL,
    ATUI	varchar2(11) NOT NULL,
    SATUI	varchar2(50),
    SAB	varchar2(40) NOT NULL,
    DEF	varchar2(4000) NOT NULL,
    SUPPRESS	char(1) NOT NULL,
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRDOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRDOC (
    DOCKEY	varchar2(50) NOT NULL,
    VALUE	varchar2(200),
    TYPE	varchar2(50) NOT NULL,
    EXPL	varchar2(1000)
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRFILES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRFILES (
    FIL	varchar2(50),
    DES	varchar2(200),
    FMT	varchar2(300),
    CLS	integer,
    RWS	integer,
    BTS	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRHIER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRHIER (
    CUI	char(8) NOT NULL,
    AUI	varchar2(9) NOT NULL,
    CXN	integer NOT NULL,
    PAUI	varchar2(10),
    SAB	varchar2(40) NOT NULL,
    RELA	varchar2(100),
    PTR	varchar2(1000),
    HCD	varchar2(100),
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRHIST'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRHIST (
    CUI	char(8),
    SOURCEUI	varchar2(100),
    SAB	varchar2(40),
    SVER	varchar2(40),
    CHANGETYPE	varchar2(1000),
    CHANGEKEY	varchar2(1000),
    CHANGEVAL	varchar2(1000),
    REASON	varchar2(1000),
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRMAP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRMAP (
    MAPSETCUI	char(8) NOT NULL,
    MAPSETSAB	varchar2(40) NOT NULL,
    MAPSUBSETID	varchar2(10),
    MAPRANK	integer,
    MAPID	varchar2(50) NOT NULL,
    MAPSID	varchar2(50),
    FROMID	varchar2(50) NOT NULL,
    FROMSID	varchar2(50),
    FROMEXPR	varchar2(4000) NOT NULL,
    FROMTYPE	varchar2(50) NOT NULL,
    FROMRULE	varchar2(4000),
    FROMRES	varchar2(4000),
    REL	varchar2(4) NOT NULL,
    RELA	varchar2(100),
    TOID	varchar2(50),
    TOSID	varchar2(50),
    TOEXPR	varchar2(4000),
    TOTYPE	varchar2(50),
    TORULE	varchar2(4000),
    TORES	varchar2(4000),
    MAPRULE	varchar2(4000),
    MAPRES	varchar2(4000),
    MAPTYPE	varchar2(50),
    MAPATN	varchar2(100),
    MAPATV	varchar2(4000),
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRRANK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRRANK (
    RANK	integer NOT NULL,
    SAB	varchar2(40) NOT NULL,
    TTY	varchar2(40) NOT NULL,
    SUPPRESS	char(1) NOT NULL
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRREL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRREL (
    CUI1	char(8) NOT NULL,
    AUI1	varchar2(9),
    STYPE1	varchar2(50) NOT NULL,
    REL	varchar2(4) NOT NULL,
    CUI2	char(8) NOT NULL,
    AUI2	varchar2(9),
    STYPE2	varchar2(50) NOT NULL,
    RELA	varchar2(100),
    RUI	varchar2(10) NOT NULL,
    SRUI	varchar2(50),
    SAB	varchar2(40) NOT NULL,
    SL	varchar2(40) NOT NULL,
    RG	varchar2(10),
    DIR	varchar2(1),
    SUPPRESS	char(1) NOT NULL,
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRSAB'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRSAB (
    VCUI	char(8),
    RCUI	char(8),
    VSAB	varchar2(40) NOT NULL,
    RSAB	varchar2(40) NOT NULL,
    SON	varchar2(3000) NOT NULL,
    SF	varchar2(40) NOT NULL,
    SVER	varchar2(40),
    VSTART	char(8),
    VEND	char(8),
    IMETA	varchar2(10) NOT NULL,
    RMETA	varchar2(10),
    SLC	varchar2(1000),
    SCC	varchar2(1000),
    SRL	integer NOT NULL,
    TFR	integer,
    CFR	integer,
    CXTY	varchar2(50),
    TTYL	varchar2(400),
    ATNL	varchar2(4000),
    LAT	char(3),
    CENC	varchar2(40) NOT NULL,
    CURVER	char(1) NOT NULL,
    SABIN	char(1) NOT NULL,
    SSN	varchar2(3000) NOT NULL,
    SCIT	varchar2(4000) NOT NULL
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRSAT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRSAT (
    CUI	char(8) NOT NULL,
    LUI	varchar2(10),
    SUI	varchar2(10),
    METAUI	varchar2(100),
    STYPE	varchar2(50) NOT NULL,
    CODE	varchar2(100),
    ATUI	varchar2(11) NOT NULL,
    SATUI	varchar2(50),
    ATN	varchar2(100) NOT NULL,
    SAB	varchar2(40) NOT NULL,
    ATV	varchar2(4000),
    SUPPRESS	char(1) NOT NULL,
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRSMAP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRSMAP (
    MAPSETCUI	char(8) NOT NULL,
    MAPSETSAB	varchar2(40) NOT NULL,
    MAPID	varchar2(50) NOT NULL,
    MAPSID	varchar2(50),
    FROMEXPR	varchar2(4000) NOT NULL,
    FROMTYPE	varchar2(50) NOT NULL,
    REL	varchar2(4) NOT NULL,
    RELA	varchar2(100),
    TOEXPR	varchar2(4000),
    TOTYPE	varchar2(50),
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRSTY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRSTY (
    CUI	char(8) NOT NULL,
    TUI	char(4) NOT NULL,
    STN	varchar2(100) NOT NULL,
    STY	varchar2(50) NOT NULL,
    ATUI	varchar2(11) NOT NULL,
    CVF	integer
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRXNS_ENG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRXNS_ENG (
    LAT	char(3) NOT NULL,
    NSTR	varchar2(3000) NOT NULL,
    CUI	char(8) NOT NULL,
    LUI	varchar2(10) NOT NULL,
    SUI	varchar2(10) NOT NULL
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRXNW_ENG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRXNW_ENG (
    LAT	char(3) NOT NULL,
    NWD	varchar2(100) NOT NULL,
    CUI	char(8) NOT NULL,
    LUI	varchar2(10) NOT NULL,
    SUI	varchar2(10) NOT NULL
)
PCTFREE 10 PCTUSED 80;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MRAUI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MRAUI (
    AUI1	varchar2(9) NOT NULL,
    CUI1	char(8) NOT NULL,
    VER	varchar2(10) NOT NULL,
    REL	varchar2(4),
    RELA	varchar2(100),
    MAPREASON	varchar2(4000) NOT NULL,
    AUI2	varchar2(9) NOT NULL,
    CUI2	char(8) NOT NULL,
    MAPIN	char(1) NOT NULL
)
PCTFREE 10 PCTUSED 80;

